### ISSUE TITLE
The scoreboard should not display negative numbers or non-numbers

### ISSUE THREAD

**Issue by lifeadventurer** [blameazu/minesweeper#4]
![image](https://github.com/user-attachments/assets/51933518-fd4f-48f2-9820-f7df4e2bcdf3)
![image](https://github.com/user-attachments/assets/b9933d14-253b-4a6d-86b3-5dba2b83995b)

**Comment by blameazu** [comment]
Fixed in commit
https://github.com/blameazu/minesweeper/commit/c4cd7836448a695f009a79b63c5d24000ae24397
